/// <reference types="vite/client" />

// Cloudflare Worker environment types are provided by @cloudflare/workers-types.
// Specific bindings from wrangler.jsonc are auto-generated by running:
//
//    pnpm wrangler types
//
// which creates worker-configuration.d.ts with the Env interface.
// That file augments the base Cloudflare.Env type from @cloudflare/workers-types.